spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tech_app?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: bestuser
    password: bestuser
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
